### ISSUE TITLE
안녕하세요. 플루터 인스타그램 클론코딩을 하고 있는 개발자입니다.

### ISSUE THREAD

**Issue by SeoJigyeong** [sudar-life/flutter_instagram_clone_p#1]
안녕하세요. 플루터 인스타그램 클론코딩을 하고 있는 개발자입니다. 
인스타그램 클론코딩을 하려고 하는데 처음부터 막히는게 버전이 충돌나서 그런거 같아서요..
근데 제가 플루터를 이제 배우기 시작해서 해당 에러를 어떻게 해결해야 할지 모르겠는데
혹시 도움을 받을 수 있을까요?
https://okky.kr/questions/1465005#answer-677883

**Comment by sudar-life** [comment]
``안녕하세요. 우선 인스타그램 클론코딩 소스 코드를 이용하여 학습해주셔서 감사합니다 :) 

문제의 원인은 photo_manager를 ^2.7.1 로 최신 소스를 사용해주시면서 발생되는 문제 입니다. 
물론 라이브러리를 최신 소스로 유지하는것은 좋긴하지만 운영프로젝트의 경우 최신 라이브러리로 업데이트하는 것은 여러가지 검증이 필요한 부분이 있습니다. 하지만 지금 단계에서는 학습이 목적이시기 때문에 문제 해결과 왜 발생되는 오류인지 설명을 드리자면 

에러 발생 이유
photo_manager 2.7.1가 사용되는 안드로이드 gradle 버전과 현 flutter_instagram_clone_p에서 사용되고 있는 gradle 버전이 맞지 않아서 발생되는 문제 입니다. 

해결방안
flutter_instagram_clone_p 에서 사용중인 gradle을 업데이트 하는 방법입니다. 
/android/build.gradle 소스 파일중 buildscript 부분을 다음과 같이 수정해줍니다. 
```
buildscript {
    ext.kotlin_version = '1.8.21'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```
/androd/gradle/wrapper 폴더내의 gradle-wrapper.properties 파일중 gradle 소스 다운로드 url인 distributionUrl을 수정합니다.
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip`

@SeoJigyeong 님 덕분에 제 소스도 최신 버전을 사용할 수 있도록 소스 코드를 업데이트를 진행하겠습니다. 
감사합니다. 
수정 이후 flutter clean 그리고 flutter pub get으로 다시 의존성을 맺어주시고 앱을 실행해주시면 될 것입니다.

**Comment by SeoJigyeong** [comment]
@sudar-life 
빠른 피드백 감사합니다!! 버전 충돌 때문이었다니 ㅠㅠ 
올려주신 버전으로 돌렸을 때 빌드 에러가 나긴했는데

```
FAILURE: Build failed with an exception.  
* What went wrong: Execution failed for task ':app:processDebugMainManifest'. 
> Unable to make field private final java.lang.String java.io.File.path accessible: 
module java.base does not "opens java.io" to unnamed module @748a52fa
```

gradle.properties 에

```
org.gradle.jvmargs=--add-opens java.base/java.io=ALL-UNNAMED
```
설정을 하니 잘 돌아갔습니다.
